### ISSUE TITLE
Roadmap 0.1

### ISSUE THREAD

**Issue by kedark3** [RedHatSatellite/satellite-ansible-compilation#16]
This is an EPIC kind of Roadmap issue that is encompassing list of items with need to do in order to get this project moving forward as a "well-oiled machine": 

- [ ] Update all existing READMEs to be accurate and useful
- [ ] Add GitHub Actions/TravisCI/JenkinsCI
- [ ] Create a **suggestive** list of standards to have the repo/PRs conforming

**Comment by Wrytarian** [comment]
Hi!  Could I help with this? I am fairly new to GitHub but would love to get involved in a project that would help me learn more. Let me know if you have any questions. Thanks!

**Comment by kedark3** [comment]
@LoisGitStuff there aer some README files under `roles/` that have broken formatting, that's a good way to start if you are new. Thanks for showing interest.

**Comment by Wrytarian** [comment]
Yay, thank you! 

It looks like this is the only readme with broken formatting: 

https://github.com/RedHatSatellite/satellite-ansible-compilation/tree/master/roles/config
  
I'm working on it but won't be able to finish tonight. Stay tuned!

**Comment by Wrytarian** [comment]
I added block code tags to the Role Variables section of the config readme and that seemed to fix the formatting issues. I also added code block tags to the Role Variables section of the readme files for rhsm and yumupdate so they would be consistent with the other readme files in the roles folder.
